on: pull_request

name: Check Reviewers

jobs:
  check:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq '. | length'
