on:
  push:
    branches:
      - master

name: Staging Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging
    env:
      RMS_EXT_API: ${{ secrets.RMS_EXT_API }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: build
        run: npm install && npm run build $RMS_EXT_API
        env:
          RMS_EXT_API: 가나다라

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://temp.sekyung.kim
